name = "CHMMera"
uuid = "4c20a592-b4de-41d1-8706-b02f346981aa"
authors = ["aronStalmarck <aron.stalmarck@gmail.com> and contributors"]
version = "0.1.2"

[compat]
Random = "1.10.8"
julia = "1.6"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
